server:
  port: 8007
spring:
  application:
    name: feignuserclass
  rabbitmq:
    host: 192.168.197.143
    username: lbaci
    password: lbaci
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://192.168.187.1:8001/eureka,http://192.168.187.1:8002/eureka
    register-with-eureka: true
    fetch-registry: true
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
logging:
  level:
    com.example.userclassprovider.feign: debug
usernametest: lsisitest
#暴露监控端点
#rabbitmq相关设置 ，暴露 bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
